### ISSUE TITLE
FrequencyBasedBootstrapping fails when something is found

### ISSUE THREAD

**Issue by zuphilip** [infolis/infoLink#42] opened 2015-11-19 23:37 UTC
Test case is http://infolis.gesis.org/infolink/api/execution/4b139d50-8f15-11e5-9bd7-f503d7e2f6dc where you also see the (usual) regexp. The [text input file](http://infolis.gesis.org/infolink/api/infolisFile/cc371cf0-8f14-11e5-9bd7-f503d7e2f6dc) was just containing one line

```
Forschungsergebnisse auf der Basis des ALLBUS 1996 und der Nürnberger BerufsschülerInnenbefragung 1999
```

The log shows

```
    DEBUG [Fri Nov 20 00:24:27 CET 2015 -- SearchTermPosition] Query: contents:ALLBUS
    DEBUG [Fri Nov 20 00:24:27 CET 2015 -- SearchTermPosition] Number of hits (documents): 1
    DEBUG [Fri Nov 20 00:24:27 CET 2015 -- FrequencyBasedBootstrapping] Lucene pattern: "Basis des * *"
    DEBUG [Fri Nov 20 00:24:27 CET 2015 -- FrequencyBasedBootstrapping] Regex: \S++\s\S++\s\S++\s\QBasis\E\s\Qdes\E\s\s?(\S*?\s?\S+?\s?\S+?\s?\S+?\s?\S*?)\s?\s\Q\E(\d{4})\Q\E\s\S+?\s\S+?\s\S+?\s\S+
    ERROR [Fri Nov 20 00:24:27 CET 2015 -- FrequencyBasedBootstrapping] Execution threw an Exception: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/html;charset=utf-8, type=class io.github.infolis.model.ErrorResponse, genericType=class io.github.infolis.model.ErrorResponse.
```

**Comment by zuphilip** [comment] 2015-11-19 23:40
The same test case with another seed `333` which will not be found is working: http://infolis.gesis.org/infolink/api/execution/7ecbd180-8f15-11e5-9bd7-f503d7e2f6dc

**Comment by kba** [comment] 2015-11-19 23:47
Do you still have the JSON? Trying to reproduce/fix this.

**Comment by kba** [comment] 2015-11-19 23:51
``` js
{
  "algorithm": "io.github.infolis.algorithm.FrequencyBasedBootstrapping",
  "inputFiles": [
    "http://infolis.gesis.org/infolink/api/infolisFile/cc371cf0-8f14-11e5-9bd7-f503d7e2f6dc"
  ],
  "seeds": [
    "ALLBUS"
  ],
  "bootstrapStrategy":"mergeAll",
  "upperCaseConstraint":"true",
  "maxIterations": 3,
  "removeBib":"false",
  "reliabilityThreshold": 0.6
}
```

**Comment by zuphilip** [comment] 2015-11-19 23:53
Yes, it should be the same as in the example https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms#frequencybasedbootstrapping except for the file.

**Comment by kba** [comment] 2015-11-19 23:54
The error you saw before was because we missed an algorithm in the data model. This is another problem with a `NullPointerException` in the backend.

**Comment by kba** [comment] 2015-11-20 00:02
https://github.com/infolis/infolis-web/blob/master/data/infolis.tson#L216 is the problem I suppose. Those should not be links but URIs of [Entities](http://infolis.gesis.org/infolink/schema/Entity)

**Comment by kba** [comment] 2015-11-20 22:00
This one was fixed by https://github.com/infolis/infoLink/commit/fd26224c1efe23767babe109fc80b8314bb29461 (c.f.http://infolis.gesis.org/infolink/api/execution/e71e07f0-8fd1-11e5-87d1-9febea864153?format=text/turtle).

**Closed as completed by kba** 2015-11-20 22:00 UTC
