### ISSUE TITLE
FederaterSearcher not properly executeable

### ISSUE THREAD

**Issue by Dommii** [infolis/infoLink#51] opened 2015-11-20 14:17 UTC
ERROR [Fri Nov 20 15:08:52 CET 2015 -- FederatedSearcher] Execution threw an Exception: javax.ws.rs.ProcessingException: javax.ws.rs.ProcessingException: Error reading entity from input stream.

``` js
{
  "algorithm": "io.github.infolis.algorithm.FederatedSearcher", 
"queryServiceClasses": [
    "io.github.infolis.resolve.DaraHTMLQueryService"
  ],
"searchQuery": "http://infolis.gesis.org/infolink/api/searchQuery/0f7e5bb0-8f90-11e5-b892-ebe524b0ac79"
}
```

**Comment by kba** [comment] 2015-11-20 14:53
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "_id" (class io.github.infolis.model.SearchQuery), not marked as ignorable (one known property: "query"])

**Comment by kba** [comment] 2015-11-20 14:57
fixed, c.f. http://infolis.gesis.org/infolink/api/execution/fbe58ea0-8f96-11e5-b892-ebe524b0ac79?format=text/turtle

**Closed as completed by kba** 2015-11-20 14:57 UTC
